// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/5/2025, 8:09:02 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/reynantolentino/reynantlntno.dev/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/reynantolentino/reynantlntno.dev/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/reynantolentino/reynantlntno.dev/src/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/reynantolentino/reynantlntno.dev/src/plugins/**/*.{js,ts,mjs}","/Users/reynantolentino/reynantlntno.dev/src/composables/**/*.{js,ts,mjs}","/Users/reynantolentino/reynantlntno.dev/src/utils/**/*.{js,ts,mjs}","/Users/reynantolentino/reynantlntno.dev/src/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/reynantolentino/reynantlntno.dev/src/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/reynantolentino/reynantlntno.dev/src/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/reynantolentino/reynantlntno.dev/src/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;