[build]
  functions = "functions"

[[edge_functions]]
  path = "/private/manage.htm"
  function = "secure-manage"

[[edge_functions]] 
  path = "/private/manage" 
  function = "secure-manage"
  
[dev]
  port = 8080  # (Optional) If you want to specify the Netlify Dev port
