[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "21"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"

[dev]
  framework = "nuxt"
  command = "npm run dev"
  port = 8888
  targetPort = 3000
  autoLaunch = false